### PR TITLE
Update README.md to add pointers to CLT BYOS docs

### PR DESCRIPTION
**Pull request by ganesp**
Updated to add pointers to BYOS docs

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by gatneil** [comment]
I think you made a PR into your own repo...shouldn't it be a PR against the main Azure repo? :)

**Comment by ganesp** [comment]
@gatneil I do not have permission to fork to Azure org. To whom to contact for permission?

**Comment by gatneil** [comment]
Are you sure? It says you forked it from the Azure org:

image

So you can't make a pull request?

**Comment by ganesp** [comment]
@gatneil 
Oh, sorry for the confusion. My first PR here :)
Did not know that we can create PR across forks.
Please review this PR:
https://github.com/Azure/azure-quickstart-templates/pull/3961

**Comment by ganesp** [comment]
@gatneil Brian Moore has merged that PR: https://github.com/Azure/azure-quickstart-templates/pull/3961
I am removing this one. Thanks.

**Pull request closed without merging**
